### ISSUE TITLE
Extract plot parameters

### ISSUE THREAD

**Issue by trinker** [jolars/eulerr#10]
I love the work here and the improvements over **venneuler**.  One thing that was nice with **venneuler** was the ability to extract the plotting parameters from the object allowing one to plot in any graphing system as I show in this gist: https://gist.github.com/trinker/31edc08d0a4ec4c73935a23040c2f6cb and producing something like:

![image](https://user-images.githubusercontent.com/1763278/28534361-6fbf30ba-706e-11e7-894b-fed1225c6bd0.png)

https://github.com/jolars/eulerr/issues/2 is a related issue that could be solved in a general way that has some function that produced plot parameters and the actual method converts that object to a visual representation in base, grid, ggplot2 or what ever system you desired.

Is there a way to currently pull the plot parameters from the fit object?

**Comment by jolars** [comment]
You can extract the centers and radii with `coef(fit)` but not the positions of the labels (since they are computed with `plot.euler()`). I am, however, hesitant to move the pertinent code into `euler()` since it would bog down the performance of the latter. Perhaps it could be moved to its own function so that you could call it separately? Another option would be to look into optimizing the label computations.

**Comment by trinker** [comment]
Yes making the euler function do the computation would slow things down.  But the intermediate function to compute locations and extract centers and radii would be nice and could feed the plot method directly or within to plot from euler.  It'd be pretty modular and would expose the important data to the user if they needed.
