### ISSUE TITLE
The fitting function gives a fitted value of 0 to the intersection of 3 circles

### ISSUE THREAD

**Issue by EduardoGCCM** [jolars/eulerr#30]
Hi,
I am starting to use your package (the diagrams look much better than with other packages) for plotting 3 sets of genes and their intersections. I get this table after fitting:

[venn fit.xlsx](https://github.com/jolars/eulerr/files/2104040/venn.fit.xlsx)

Is there any way of making the function not to "ignore" the a&b&c intersection?

**Comment by jolars** [comment]
Did you try the `shape = "ellipse"` option? Three-set diagrams are sometimes impossible with circles.

I am closing this because it is not really an issue. I do not intend to design any explicit way of modifying the diagram since the layout is based on optimizing a loss function. It is, however, likely that eulerr will feature other loss functions in the future.
