### ISSUE TITLE
Option to add numbers plot

### ISSUE THREAD

**Issue by cdeterman** [jolars/eulerr#6]
With the `VennDiagram` package the user can have numbers directly on the plots which you can see [here](https://rstudio-pubs-static.s3.amazonaws.com/13301_6641d73cfac741a59c0a851feb99e98b.html).  Having the option to put the counts (i.e. the `original` in the `eulerr` class output) would be useful.

**Comment by jolars** [comment]
Yup, thanks. It's on my to-do list.

**Comment by jolars** [comment]
@cdeterman How do you reckon intersections that are present in the input but not in the fit should be visualized? Should they be plotted next to the plot (as a legend)?

**Comment by cdeterman** [comment]
I would agree that they should be plotted next to the plot.  Perhaps a 'warning' message noting that the intersections are present in the input but not the fit?

**Comment by jolars** [comment]
Okay. I've added an argument that labels unique sections with their respective counts. I do not think adding a warning message is necessary; the output from printing the fit should be sufficient. However, I think it's a good idea to visualize missing values on the side but I'm shelving it for now due to time constraints.

Note that this functionality is currently very slow. I'm not sure how to speed it up without moving it to c++, but I'll look into it later.
